-- require("plugins.treesitter")
require("settings.options")
require("settings.keymap")
require("settings.plugins")

require("plugins.theme")

require("plugins.autopairs")
require("plugins.autotag")
require("plugins.bufferline")
require("plugins.cmp")
require("plugins.colorizer")
require("plugins.comment")
require("plugins.dashboard")
require("plugins.formatter")
require("plugins.lsp")
require("plugins.lspkind")
require("plugins.lualine")
require("plugins.tree")
require("plugins.spectre")
require("plugins.whichkey")
require("plugins.matchtag")
